@apiURL=https://email-service-git-email-service-api.2.rahtiapp.fi
@token={{$dotenv JWT_SECRET}}


###
POST https://email-service-git-email-service-api.2.rahtiapp.fi/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOTY2IiwibmFtZSI6IlZpY2EgRWxlcnMiLCJlbWFpbCI6ImVsZXJzdmljQGFyY2FkYS5maSIsInJvbGUiOiJFbWFpbCBTZXJ2aWNlIEFkbWluIn0.YrEN2cf48Lz9Of6IEq3MsGBwDy4mWFw2owbg6bPfzbU

{
    "subject": "Test Email",
    "body": "This is a JWT test email, please pay no attention to this \n ShadowTheVica"
}


###
POST https://email-service-git-email-service-api.2.rahtiapp.fi/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOTY2IiwibmFtZSI6IlZpY2EgRWxlcnMiLCJlbWFpbCI6ImVsZXJzdmljQGFyY2FkYS5maSIsInJvbGUiOiJFbWFpbCBTZXJ2aWNlIEFkbWluIn0.YrEN2cf48Lz9Of6IEq3MsGBwDy4mWFw2owbg6bPfzbU

{
    "subject": "Order Confirmation",
    "body": [
        {
            "orderId": 1,
            "userId": 333,
            "timestamp": "2025-02-25T13:44:42.983Z",
            "shipping_address": "My address",
            "orderPrice": "77.95",
            "orderItems": [
                {
                    "order_item_id": 1,
                    "order_id": 1,
                    "product_id": "123-CORONA",
                    "product_name": "Corona",
                    "quantity": 2,
                    "product_price": "12.99",
                    "total_price": "25.98",
                    "product_description": "Description here.",
                    "product_image": "/uploads/1740587181163-karhu-46-burk.jpg",
                    "product_country": "Mexico",
                    "product_category": "Lager"
                }
            ]
        }
    ]
}