openapi: 3.0.0
info:
  title: Email API
  description: API key available in Discord soon. JWT not working atm.
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: https://email-service-git-email-service-api.2.rahtiapp.fi
paths:
  /newsletter:
    post:
      summary: Send newsletters
      parameters:
        - name: API key
          in: query
          description: API key required for authorization.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Send newsletters.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    to:
                      type: string
                    subject:
                      type: string
                    body:
                      type: string
  /order:
    post:
      summary: Send order confirmation
      parameters:
        - name: JWT
          in: query
          description: JWT required for authorization.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Send order confirmations.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    to:
                      type: string
                    subject:
                      type: string
                    body:
                      type: string 