openapi: 3.0.0
info:
  title: Email API
  description: Only existing emails will recieve an email back. Please DO NOT use a non-existant email, thank you!
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: https://email-service-git-email-service-api.2.rahtiapp.fi
paths:
  /invoicing:
    post:
      summary: Send invoice.
      description: Attach PDF file as base64 string.
      parameters:
        - name: JWT
          in: query
          description: JWT required for authorization.
          required: true
          schema:
            type: string
      requestBody:
        description: Send invoice.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  to:
                    type: string
                    example: username@arcada.fi
                  subject:
                    type: string
                    example: Invoice
                  body:
                    type: string
                    example: Invoice details here.
                  base64:
                    type: string
                    example: base64String
        required: true
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Invoice sent.
        '400':
          description: Invalid input
  /newsletter:
    post:
      summary: Send newsletters
      parameters:
        - name: API key
          in: query
          description: API key required for authorization.
          required: true
          schema:
            type: string
      requestBody:
        description: Send newsletter.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  to:
                    type: string
                    example: username@arcada.fi
                  subject:
                    type: string
                    example: Newsletter
                  body:
                    type: string
                    example: Newsletter here.
        required: true
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Newsletter sent.
        '400':
          description: Invalid input
  /order:
    post:
      summary: Send order confirmation
      parameters:
        - name: JWT
          in: query
          description: JWT required for authorization.
          required: false
          schema:
            type: string
      requestBody:
        description: Send order confirmation.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  subject:
                    type: string
                    example: Order confirmation
                  body:
                    type: array
                    example: Order confirmation here.
                    orderitems:
                      type: array
                      example: Order items here.
        required: true
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Order confirmation sent.
        '400':
          description: Invalid input
  /shipping:
    post:
      summary: Send shipping information.
      parameters:
        - name: JWT
          in: query
          description: JWT required for authorization.
          required: true
          schema:
            type: string
      requestBody:
        description: Send shipping details.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  subject:
                    type: string
                    example: Shipping
                  body:
                    type: string
                    example: Shipping details here.
        required: true
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Shipping details sent.
        '400':
          description: Invalid input