openapi: 3.0.0
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: https://email-service-git-email-service-api.2.rahtiapp.fi
paths:
  /newsletter:
    post:
      summary: Send newsletters
      responses:
        '200':
          description: Send newsletters.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    to:
                      type: string
                    subject:
                      type: string
                    body:
                      type: string